# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np 

#### Create an array of 10 zeros 

In [4]:
number = np.zeros(10)
number

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
number_one = np.ones(10)
number_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [12]:
number_two = np.full(10,5)
number_two

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [14]:
number_three = np.arange(10,51)
number_three

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [16]:
number_four = np.arange(5,26)
number_four + number_four

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
number_five = np.array(([0,1,2],[3,4,5],[6,7,8]))
number_five

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [19]:
number_six = np.eye(3)
number_six

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [20]:
number_seven = np.random.rand(1)
number_seven

array([0.21185363])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
number_eight = np.random.randn(5,5)
number_eight

array([[-0.32340764, -0.11615542,  0.0317845 ,  2.03147384, -1.44309923],
       [ 0.17900296, -1.56306803, -1.92077102, -1.98994803, -1.05122089],
       [ 0.24178296, -0.61254691,  0.40017563,  1.15801163,  1.18428129],
       [ 1.21726383, -0.31648337,  0.95620129, -0.30107607, -0.29671927],
       [-0.55759119, -1.26289944,  0.66164988, -0.11245612,  0.12658002]])

#### Create the following matrix:

In [31]:
number_nine = np.arange(1,101).reshape(10,10)
number_nine * 0.01

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [42]:
number_ten = np.linspace(0,20,20)
number_ten

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [43]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
mat[2:5, 1:5] #2:5Baris dan 1:5Kolom

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [74]:
mat[3, 4]#Mencari 20

20

In [75]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [97]:
mat[4]

array([21, 22, 23, 24, 25])

In [98]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [100]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [103]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [110]:
jumlah = np.sum(mat, axis=0)
jumlah

array([55, 60, 65, 70, 75])

# Great Job!